add missing facts to tests
this made puppet6 crash:

```
   # NoMethodError:
   #   undefined method `downcase' for nil:NilClass
   #   ./vendor/bundle/ruby/2.4.0/gems/puppet-6.14.0/lib/puppet/provider/service/init.rb:24:in `block in <top (required)>'
3) patterndb::raw::ruleset Raw rulesets with directory is expected to contain File[BASEDIR/etc/syslog-ng/patterndb.d/default/myrawruleset] with ensure => "directory"
```